background = "#e8f1f9"
foreground = "#e8f1f9"
border_color = "#000000"
border_radius = 10
border_width = 0

[rows]
background = "#e8f1f9"
text_color = "#ffffff"
border_color = "#000000"
border_radius = 0
border_width = 0
width = "shrink"
height = "fill"
padding = 0
[rows.lines.default]
background = "#000000"
text_color = "#18405a"
border_color = "#000000"
border_radius = 0
border_width = 0
width = "fill"
height = "shrink"
padding = 4

[rows.lines.selected]
background = "#63b4fb"
text_color = "#0000ff"
border_color = "#000000"
border_radius = 5
border_width = 0
width = "fill"
height = "shrink"
padding = 5

[scrollable]
background = "#000000"
border_color = "#000000"
border_radius = 0
border_width = 0
height = "fill"
width = "fill"
padding = 0
scrollbar_width = 10
scroller_width = 10

[scrollable.scroller]
color = "#314c84"
border_color = "#314c84"
border_radius = 4
border_width = 1

[search]
background = "#000000"
text_color = "#000000"
width = "fill"
height = "40"
padding = 4
border_color = "#000000"
border_radius = 0
border_width = 0

[search.bar]
background = "#e8f1f9"
value_color = "#000000"
placeholder_color = "#fcfbfb"
border_color = "#00ff00"
selection_color = "#fcfbfb"
border_radius = 6
border_width = 0
text_width = "fill"

[menu]
background = "#63b4fb"
text_color = "#ffffff"
border_color = "#63b4fb"
border_radius = 6
border_width = 10
width = "fill"
height = "shrink"
padding = 10
[menu.lines.default]
background = "#000000"
text_color = "#000000"
border_color = "#000000"
border_radius = 0
border_width = 0
width = "shrink"
height = "fill"
padding = 5

[menu.lines.selected]
background = "#314c84"
text_color = "#000000"
border_color = "#314c84"
border_radius = 3
border_width = 2
width = "fill"
height = "shrink"
padding = 5
